# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'whatever.$(Build.BuildId)'
  RAMP_UP: '1'
  DARATION: '60'
  VUSERS: '10'

stages:
- stage: Build 
  displayName: Build JMeter image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Bash@3
      displayName: Performance Test
      inputs:
        targetType: 'inline'
        script: |
         docker images 
         docker build -t test_perfmeter .
         docker images 
         mkdir report 
         docker rm debug_perfmeter
         docker run --rm -v $(Build.SourcesDirectory)/reports:/tmp/reports  -e JVM_ARGS="-Xms1g -Xmx1g" -e junit_report="True" -v /tmp/reports:/tmp/reports getcarrier/perfmeter:2.0.5.3 -n -t /mnt/jmeter/FloodIO.jmx -JVUSERS=${{ variables.VUSERS }} -JRAMP_UP=${{ variables.RAMP_UP }} -JDURATION=${{ variables.DARATION }}

         ls -la reports

        workingDirectory: '$(System.DefaultWorkingDirectory)/_florykiank_perfmeter'
        displayName: 'Command Line Script'
          #docker run --name debug_perfmeter  getcarrier/perfmeter:whatever.$(Build.BuildId) -n -t /mnt/jmeter/FloodIO.jmx -JVUSERS=${{ variables.VUSERS }} -JRAMP_UP=${{ variables.RAMP_UP }} -JDURATION=${{ variables.DARATION }}
          #docker images
          #docker run --name debug_perfmeter -v $(Build.SourcesDirectory)/reports:/tmp/reports -e junit_report=True getcarrier/perfmeter:1.5 -n -t /mnt/jmeter/FloodIO.jmx -JVUSERS=$(VUSERS ) -JRAMP_UP=$(RAMP_UP) -JDURATION=$(DARATION) -j /tmp/reports/jmeter_$(date +%s).log -l /tmp/reports/jmeter_$(date +%s).jtl -e -o /tmp/reports/HtmlReport_$(date +%s)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop1
          
#     - task: Bash@3
#       displayName: Publish
#       inputs:
#         targetType: 'inline'
#         script: |
#           docker build -t perfmeter:1.5.1

